use customer_behaviour;
select * from data;


-- What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue
from data
group by gender;


-- Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from data 
where discount_applied = 'Yes' 
and purchase_amount >= (select AVG(purchase_amount) from data);


--  Which are the top 5 products with the highest average review rating ?
select item_purchased, round(avg(review_rating), 2) as avg_product_rating
from data
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
round(avg(purchase_amount), 2)
from data
where shipping_type = 'Standard'
or shipping_type = 'Express'
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
count(customer_id) AS total_customers,
round(AVG(purchase_amount), 2) AS avg_spend,
round(SUM(purchase_amount), 2) AS total_revenue
FROM data
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 1.0/COUNT(*), 2) AS discount_rate
FROM data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with cte as (
SELECT customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM data)

select customer_segment, count(*) AS "Number of Customers" 
from cte 
group by customer_segment;

-- What are the top 3 most purchased products within each category? 
WITH cte AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
rank() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rnk
FROM data
GROUP BY category, item_purchased
)
SELECT rnk, category, item_purchased, total_orders
FROM cte
WHERE rnk <=3;
 
-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select round((select count(subscription_status) from data where subscription_status = 'Yes')*100*1.0/(select count(subscription_status) from data), 2) as rate
from data 
where purchase_frequency_days > 5
group by rate;

-- What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as revenue
from data 
group by age_group;